

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "main\HisPlus-Service-Local-Tests\App.config"
//     Connection String Name: "AppPlus.His"
//     Connection String:      "Data Source=localhost;Initial Catalog=HIS;Persist Security Info=True;User ID=sa;password=**zapped**;;MultipleActiveResultSets=True"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Enterprise Edition (64-bit)
// Database Engine Edition: Enterprise

namespace Xy.Pis.Domain
{

}

