

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "main\HisPlus-Code-Generator\App.config"
//     Connection String Name: "HisPlus"
//     Connection String:      "Data Source=192.168.1.225;Initial Catalog=GBLNHISShow;UID=his;password=**zapped**;;Application Name=HisPlus Code Generator"
// ------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HisPlus.Contract.Messages;
using HisPlus.Contract.Services;
using HisPlus.Core.Abstractions.Support;
using HisPlus.Domain;

namespace HisPlus.Services
{
}

