

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "main\AppPlus-Code-Generator\App.config"
//     Connection String Name: "AppPlus.His"
//     Connection String:      "Data Source=192.168.1.225;Initial Catalog=GBLNHISShow;UID=his;password=**zapped**;;Application Name=AppPlus Code Generator"
// ------------------------------------------------------------------------------------------------
using System.ServiceModel;
using AppPlus.Infrastructure.Contract.Services;
using HisPlus.Contract.Messages;

namespace HisPlus.Contract.Services
{
}

