

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "main\HisPlus-Service-UnitTests\App.config"
//     Connection String Name: "HisPlus"
//     Connection String:      "Data Source=localhost;Initial Catalog=HisPlus;Persist Security Info=True;User ID=sa;password=**zapped**;;MultipleActiveResultSets=True"
// ------------------------------------------------------------------------------------------------
using System.Data.Entity.ModelConfiguration;

namespace HisPlus.Domain.Mapping
{
}

