

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "main\AppPlus-Code-Generator\App.config"
//     Connection String Name: "AppPlus.His"
//     Connection String:      "Data Source=(local);Initial Catalog=HIS;Integrated Security=True;Application Name=AppPlus Code Generator"
// ------------------------------------------------------------------------------------------------
using AppPlus.Infrastructure.Contract.Messages;

namespace HisPlus.Contract.Messages
{
}

